# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

AS3_ACCESS_KEY: "AKIAJBFKKAS3OAXLUOAQ"
AS3_SECRET_ACCESS_KEY: "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"
AS3_BUCKET_NAME: "home_sit"
EMAIL_ADDRESS: "stewartimel@gmail.com"
EMAIL_PASSWORD: "MCDcoffee124"
GOOGLE_CLIENT_ID: "527876756740-5ei7igtcd6t4s8drtqjsitfdjqh4k2gq.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "xCq6k51ID50LgvL4rc-kuccp"
