AS3_ACCESS_KEY: "AKIAJAFWM4UFF6ES3EIQ"
AS3_SECRET_ACCESS_KEY: "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"
AS3_BUCKET_NAME: "home_sit"
GOOGLE_CLIENT_ID: "527876756740-5ei7igtcd6t4s8drtqjsitfdjqh4k2gq.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "xCq6k51ID50LgvL4rc-kuccp"
